### ISSUE TITLE
ethernet configuration 

### ISSUE THREAD

**Issue by pebauer68** [rockchip-linux/rk-rootfs-build#1]
Please include an out-of-the-box config that allows to get an IP-address on device startup via DHCP. on Eth0 e.g. an entry in /etc/network/interfaces

**Comment by wzyy2** [comment]
It seems that debian use networkmanager and I don't know how to set up it out-of-the-box.
Usually I enable "Auto Ethernet" manually after installation.

**Comment by pebauer68** [comment]
Thank you for the info jacob,
You are right, the networkmanager hides its configuration somewhere for
enabling/disabling interfaces. The whole thing is a bit painful.

Thank You,
Peter

**Comment by wzyy2** [comment]
Have update network-manager to 1.2 and it can get an IP-address on device startup via DHCP out-of-the-box now.
