### ISSUE TITLE
Mali-400MP Utgard Linux fbdev user space binaries request

### ISSUE THREAD

**Issue by omegamoon** [rockchip-linux/rk-rootfs-build#11]
Could you please provide user space binaries for Mali-400MP (Utgard) on Linux, fbdev only, so *without* dependencies on X11 libraries? I need them for use in OpenELEC

More details of what I would like is:
* Linux
* hard float
* fbdev
* dma_buf
* no profiling

Corresponding Mali kernel driver (API) is currently r6p0-01rel1

**Comment by wzyy2** [comment]
Sorry, we won't release fbdev mali binarys. Fbdev mali binarys are for old 3.10 kernel which we don't plan to give support.
