### ISSUE TITLE
Support glvnd?

### ISSUE THREAD

**Issue by phhusson** [rockchip-linux/rk-rootfs-build#12]
It don't know if it's possible, but having glvnd would be nice.
This would enable the user to have both mesa and mali installed alongside.
This way, it is easier to get OpenGL (non-ES) headers, which is required to build many apps.

Also this could be useful to select between mesa and glshim

**Comment by wzyy2** [comment]
If you just need OpenGL (non-ES) headers, you can simply download libgl1-mesa-dev and extract it.
