### ISSUE TITLE
sshd not inited?

### ISSUE THREAD

**Issue by phhusson** [rockchip-linux/rk-rootfs-build#13]
When building the rootfs in the docker-rockchip, no ssh key is pre-generated in /etc/ssh/sshd_host_rsa_key this makes sshd not working until the key is generated through serial.

I'm not too sure if this is supposed to be done on the host, or on first boot, but either way, it didn't happen to me.

I have this bug on rk-rootfs-build @ e0c5b70a2f6c45fef7920f3ad98387928457e0f7

**Comment by wzyy2** [comment]
https://github.com/rockchip-linux/rk-rootfs-build/blob/master/overlay/etc/rc.local

It can be generated on first boot, but i had commented the code because i got some errors when excuting "dpkg-reconfigure openssh-server".

Could you help me test it?
If there is no errors with "dpkg-reconfigure openssh-server" now, i will revert it.

**Comment by phhusson** [comment]
Decommenting it does work.
I'll try to generate a rootfs with this change to confirm.

FWIW, the rc.local checks for /etc/ssh/ssh_host_dsa_key which is NOT generated.
Nowadays only rsa/ecdsa are generated, so the test -f would have to be on /etc/ssh/ssh_host_rsa_key

**Comment by phhusson** [comment]
Right, I've found the issue you most likely were experiencing.
With systemd, there are two possibilities to do sshd:
- First one is to have systemd itself listen on port 22, and fork to sshd with the client socket (this is ssh.socket)
- Second one is classic method, with sshd always running and listening on port 22 (this is ssh.service)

In current configuration, ssh.socket starts by default.
Though dpkg-reconfigure openssh-server, starts ssh.service.
For some reason (probably because of the parallelism of systemd), when called from rc.local, dpkg-reconfigure will fail to start ssh.service, because ssh.socket is already binding on port 22.

This is because of the way this is done in debian. Most distributions just have ssh-keygen -A in prestart of the service and socket.

My suggested fix is to use ssh-keygen -A in rc.local. This way, we keep debian's ssh.socket/ssh.service, we create the keys, but don't perturb the way ssh is supposed to work.

This is not 100% ideal, because if ssh.service is chosen instead of ssh.socket, and ssh.service is started before rc.local, then it will fail to start on first boot, because it has no key.
This is not the case at the moment.

So, I believe this is a fix simple enough (doesn't need to rewrite ssh.socket/ssh.service), though complete enough for this use-case.

**Comment by wzyy2** [comment]
Thank you
:smile:
