### ISSUE TITLE
alsa-base not available on debian stretch

### ISSUE THREAD

**Issue by gooze74** [rockchip-linux/rk-rootfs-build#15]
base-debian build is failing because of missing package alsa-base which does not exist in debian stretch : 
[https://packages.debian.org/search?keywords=alsa-base&searchon=names&suite=all&section=all](https://packages.debian.org/search?keywords=alsa-base&searchon=names&suite=all&section=all)

```
Building dependency tree...
Reading state information...
Package alsa-base is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'alsa-base' has no installation candidate
```

**Comment by wzyy2** [comment]
Thx, i will remove it.
