### ISSUE TITLE
libmali for arm64?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [rockchip-linux/rk-rootfs-build#17]
Hello, I am attempting to get the mali drivers working for the RK3399, however in the rockchip.sh, i see these lines:
```
    dpkg -i  /packages/libmali/lib*mali-rk-midgard-4th-r13p0_*.deb
    dpkg -i  /packages/libmali/libmali-rk-dev_*.deb
```

But I cannot find the r13p0 debs anywhere.

**Comment by wzyy2** [comment]
At present we only focus on 32-bit userspace.

https://github.com/rockchip-linux/libmali/blob/rockchip/lib/arm-linux-gnueabihf/lib32mali-midgard-4th-r13p0.so
