### ISSUE TITLE
how to resolve the "libc6" problem?

### ISSUE THREAD

**Issue by xuie0000** [rockchip-linux/rk-rootfs-build#18]
```
$ sudo apt-get install binfmt-support qemu-user-static
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libc-bin : Depends: libc6 (< 2.20) but 2.21-0ubuntu4.3 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

```
$ cat /proc/version 
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.43-2 (2017-04-30)
```

this is my exp log, i can't deal it, tks.

**Comment by wzyy2** [comment]
uh.. - - I think it's your host pc problem.
I have no idea.

**Comment by BiatuAutMiahn** [comment]
good around for a solution, issue does not look relevant to this repo.

Run this and post output...
apt-get -f install

**Comment by xuie0000** [comment]
@BiatuAutMiahn i have try, but 2.21-0ubuntu4.3 (>2.20), failed

**Comment by xuie0000** [comment]
@wzyy2 用Debian系统太不靠谱了，能不能分享一份Ubuntu的编译？我用最新的debian系统，包装一些简单的包，如 git, curl这些都说不能安装，更别说其它的了。

这个错误是因为我用了一些source.list是ubuntu的，来安装一些软件（如chrome和fcitx）而出现了libc6都出错了。支持的包实在惨不忍睹

今天上午我安装一个Debian7.8的，直接安装到一半就说错误，**安装失败**，最新的Debian8.8软件包太多坑了，实在找不到理由这个项目有很多人在使用？

你的系统是多少的？我去下截一个你用的系统版本来编译，贼伤、

**Comment by wzyy2** [comment]
en... Do you use debian host to compile? 
You can't add ubuntu source to debian, it will break dependencies...


If you want to use ubuntu to compile, just use it.

**Comment by BiatuAutMiahn** [comment]
in any case, id either reload ur distro, or install virtual box, and compile with a live cd iso
