### ISSUE TITLE
RK3328/RK3399: Missing arm64 libmali packages causes rockchip.sh to fail

### ISSUE THREAD

**Issue by mmeyer724** [rockchip-linux/rk-rootfs-build#19]
This block calls for `lib32mali-rk-utgard-2th-r7p0_*.deb` and `libmali-rk-dev_*.deb` to be installed:
https://github.com/rockchip-linux/rk-rootfs-build/blob/master/overlay/etc/init.d/rockchip.sh#L18

But those packages are not built for arm64:
https://github.com/rockchip-linux/rk-rootfs-build/tree/master/packages/arm64/libmali

**Comment by wzyy2** [comment]
We didn't maintain arm64 debian.

If you want to use it, you have to pack debian deb by yourself.

 For cross build:
https://github.com/rockchip-linux/docker-rockchip
