### ISSUE TITLE
BOARD in mk-image.sh

### ISSUE THREAD

**Issue by sghazagh** [rockchip-linux/rk-rootfs-build#22]
Hi,
In line 6 of script mk-image.sh, it is looking for variable BOARD:
echo Making rootfs for ${BOARD} board!

This variable is not exist, so how it know for instance to make the image for "Tinker Board" or "FireFly"

**Comment by wzyy2** [comment]
It's added by mistakes, i will remove it...
The rootfs image are generic.

**Comment by sghazagh** [comment]
correct, I realized that and updated my message...

Got it now...
