### ISSUE TITLE
cannot create /media/jerry/NDISK/rockchip/rk-rootfs-build/ubuntu-build-service/stretch-desktop-armhf/chroot/test-dev-null: Permission denied

### ISSUE THREAD

**Issue by luwanjia** [rockchip-linux/rk-rootfs-build#23]
Hi,
 I got some errors while building base-debian.
  System: Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

> Distributor ID:	Debian
Description:	Debian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch

  Command: TARGET=base ARCH=armhf ./mk-base-debian.sh

  Log is like this:
> I: Retrieving zlib1g 1:1.2.8.dfsg-5
I: Validating zlib1g 1:1.2.8.dfsg-5
P: If the following stage fails, the most likely cause of the problem is with your mirror configuration or a caching proxy.
P: Running debootstrap... 
P: Bootstrap will be foreign
/usr/sbin/debootstrap: 1450: /usr/sbin/debootstrap: cannot create /media/jerry/NDISK/rockchip/rk-rootfs-build/ubuntu-build-service/stretch-desktop-armhf/chroot/test-dev-null: Permission denied
E: Cannot install into target '/media/jerry/NDISK/rockchip/rk-rootfs-build/ubuntu-build-service/stretch-desktop-armhf/chroot' mounted with noexec or nodev
P: Begin unmounting filesystems...
P: Saving caches...
if [ -f binary-tar.tar.gz ]; then \
	tar -jcf linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 auto/ config/ configure; \
	sudo mv binary.contents linaro-stretch-alip-`date +%Y%m%d`-1.contents; \
	sudo mv chroot.packages.live linaro-stretch-alip-`date +%Y%m%d`-1.packages; \
	sudo mv binary-tar.tar.gz linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz; \
	md5sum linaro-stretch-alip-`date +%Y%m%d`-1.build-log.txt linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 linaro-stretch-alip-`date +%Y%m%d`-1.contents linaro-stretch-alip-`date +%Y%m%d`-1.packages linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz > linaro-stretch-alip-`date +%Y%m%d`-1.md5sums.txt; \
	sha1sum linaro-stretch-alip-`date +%Y%m%d`-1.build-log.txt linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 linaro-stretch-alip-`date +%Y%m%d`-1.contents linaro-stretch-alip-`date +%Y%m%d`-1.packages linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz > linaro-stretch-alip-`date +%Y%m%d`-1.sha1sums.txt; \
fi

How can I do for this? Thank you.

**Comment by luwanjia** [comment]
And also failed with command: TARGET=desktop ARCH=armhf ./mk-base-debian.sh

> I: Validating zlib1g 1:1.2.8.dfsg-5
P: If the following stage fails, the most likely cause of the problem is with your mirror configuration or a caching proxy.
P: Running debootstrap... 
P: Bootstrap will be foreign
/usr/sbin/debootstrap: 1450: /usr/sbin/debootstrap: cannot create /media/jerry/NDISK/rockchip/rk-rootfs-build/ubuntu-build-service/stretch-desktop-armhf/chroot/test-dev-null: Permission denied
E: Cannot install into target '/media/jerry/NDISK/rockchip/rk-rootfs-build/ubuntu-build-service/stretch-desktop-armhf/chroot' mounted with noexec or nodev
P: Begin unmounting filesystems...
P: Saving caches...
if [ -f binary-tar.tar.gz ]; then \
	tar -jcf linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 auto/ config/ configure; \
	sudo mv binary.contents linaro-stretch-alip-`date +%Y%m%d`-1.contents; \
	sudo mv chroot.packages.live linaro-stretch-alip-`date +%Y%m%d`-1.packages; \
	sudo mv binary-tar.tar.gz linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz; \
	md5sum linaro-stretch-alip-`date +%Y%m%d`-1.build-log.txt linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 linaro-stretch-alip-`date +%Y%m%d`-1.contents linaro-stretch-alip-`date +%Y%m%d`-1.packages linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz > linaro-stretch-alip-`date +%Y%m%d`-1.md5sums.txt; \
	sha1sum linaro-stretch-alip-`date +%Y%m%d`-1.build-log.txt linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 linaro-stretch-alip-`date +%Y%m%d`-1.contents linaro-stretch-alip-`date +%Y%m%d`-1.packages linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz > linaro-stretch-alip-`date +%Y%m%d`-1.sha1sums.txt; \
fi

**Comment by wzyy2** [comment]
I think it might be due to NTFS.

**Comment by luwanjia** [comment]
My disk format is ext4, not ntfs.
![gnome-shell-screenshot-6ado4y](https://user-images.githubusercontent.com/23115071/29150050-bd9b0d7e-7daa-11e7-85c4-11df0b9fb58a.png)

**Comment by jwinarske** [comment]
Hit this problem with ARCH=armhf and ARCH=arm64.
