### ISSUE TITLE
为什么没有arm64 packages

### ISSUE THREAD

**Issue by ghost** [rockchip-linux/rk-rootfs-build#26]
想为rk3399编译文件系统, 传入命令行参数ARCH=arm64, 发现packages下无arm64相关软件, 这个要怎么处理.ps:armhf 编译的文件系统以及可以在rk3399上运行

**Comment by wzyy2** [comment]
You have to rebuild them by yourself.
:-)

**Comment by tiny-tiger** [comment]
感谢回复, 您的意思是我要自己从git仓库下载, 然后在小机上编译安装就能达到package安装一样的效果吗, 相应的测试用例可以做测试使用吗

**Comment by rkchrome** [comment]
最新已经支持
