### ISSUE TITLE
fail to run test_dec-gst.sh and test_dec-qt.sh

### ISSUE THREAD

**Issue by wuweidong0107** [rockchip-linux/rk-rootfs-build#28]
Hi, I'm using kernel at this commit (https://github.com/rockchip-linux/kernel/commit/77c621e5319e4b78cb04cc00699f1877627ccc05)

my build step:
make ARCH=arm64 rockchip_linux_defconfig
make ARCH=arm64 CROSS_COMPILE=aarch64-linux- rk3399-sapphire-excavator-linux.img -j16

And using rootfs at this commit (https://github.com/rockchip-linux/rk-rootfs-build/commit/34befe238d68f7af6792f2ee0ba4218563d6ec81)

Here's my problem:
**Fail to run test_dec-gst.sh. Got log:**
	Setting pipeline to PAUSED ...
	Pipeline is PREROLLING ...
	Redistribute latency...
	Redistribute latency...
	ERROR: from element /GstPipeline:pipeline0/GstURIDecodeBin:urideecodeBin:decodebin0/GstQTDemux:qtdemux0: Internal data stream error.
	Additional debug info:
	qtdemux.c(5850): gst_qtdemux_loop stPipeline:pipeline0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
	streaming stopped, reason not-nated (-4)
	ERROR: pipeline doesn't want to preroll.
	Setting pipeline to NULL ...
	Freeing pipeline …

**Fail to run  test_dec-qt.sh. Got log:**
 	** (player:1177): CRITICAL **: gst_dmabuf_memory_get_fd: assertion 'gst_is_dmabuf_memory (mem)' failed
	** (player:1177): CRITICAL **: gst_dmabuf_memory_get_fd: assertion 'gst_is_dmabuf_memory (mem)' failed
	…

Any suggestion? Thanks.

**Comment by wzyy2** [comment]
export GST_DEBUG=*:2

**Comment by wuweidong0107** [comment]
export GST_DEBUG=*:2:
[2.txt](https://github.com/rockchip-linux/rk-rootfs-build/files/1637458/2.txt)

export GST_DEBUG=*:5:
[5.txt](https://github.com/rockchip-linux/rk-rootfs-build/files/1637459/5.txt)

**Comment by wzyy2** [comment]
"avdec_h264" , so it have error in building rootfs.....

**Comment by wzyy2** [comment]
make sure you have gstreamer-rockchip installed

**Comment by wuweidong0107** [comment]
Fixed:
[ -e /packages/video/mpp/librockchip-mpp1_*_armhf.deb  ] && dpkg -i  /packages/video/mpp/librockchip-mpp1_*_armhf.deb
[ -e /packages/video/mpp/librockchip-mpp-dev_*_armhf.deb  ] && dpkg -i  /packages/video/mpp/librockchip-mpp-dev_*_armhf.deb
[ -e /packages/video/mpp/librockchip-vpu0_*_armhf.deb  ] && dpkg -i  /packages/video/mpp/librockchip-vpu0_*_armhf.deb

--->

ls packages/video/mpp/librockchip-mpp1_*_armhf.deb 2>/dev/null 1>&2 && dpkg -i  /packages/video/mpp/librockchip-mpp1_*_armhf.deb
ls /packages/video/mpp/librockchip-mpp-dev_*_armhf.deb 2>/dev/null 1>&2 && dpkg -i  /packages/video/mpp/librockchip-mpp-dev_*_armhf.deb
ls /packages/video/mpp/librockchip-vpu0_*_armhf.deb 2>/dev/null 1>&2 && dpkg -i  /packages/video/mpp/librockchip-vpu0_*_armhf.deb
