### ISSUE TITLE
opencl

### ISSUE THREAD

**Issue by Vernon-github** [rockchip-linux/rk-rootfs-build#29]
Hi

In the rk3399 Linux debian system,  /usr/lib/libmaliopencl.so and /usr/lib/libopencl.so, 
what are the differences?
What's their version number?

**Comment by Vernon-github** [comment]
How to get the libOpenCL.so source code?

**Comment by wzyy2** [comment]
LibOpenCL.so is just a symbolic link to libmali.so, and libmali is close-source.
To use OpenCl API, you just need link your program with libmali library.

**Comment by Vernon-github** [comment]
What is the version of OpenCL?

**Comment by wzyy2** [comment]
I think there are some OpenCL API can print its version.

**Comment by Vernon-github** [comment]
Ok, thank you very much
