### ISSUE TITLE
libgbm.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pebauer68** [rockchip-linux/rk-rootfs-build#3]
https://github.com/rockchip-linux/rk-rootfs-build/releases/tag/release-20161013

from /var/log/Xorg.0.log
3308380.168 Failed to load /usr/lib/xorg/modules/libglamoregl.so:
libgbm.so: cannot open shared object file: No such file or directory

find . -name libgbm.so
./media/linaro/f65f9fd2-75d5-4596-96c5-2bb7aa0de6f1/usr/lib/arm-linux-gnueabihf/libgbm.so
Where should this library be copied to ?

**Comment by wzyy2** [comment]
Hi, sorry...
I make a mistake here.. 
Please not use release-20161013.

I'will fix it next Monday.

**Comment by wzyy2** [comment]
I update new release.
Please make sure you are using latest release-4.4 kernel(matching mali-gpu version) and don't forget to update you extlinux.conf since commit(https://github.com/rockchip-linux/kernel/commit/a0a1e633bc191a30c91a11ca14af3fafb8c0c46f) was merged in.
