### ISSUE TITLE
Is the instruction for building arm64 rootfs correct?

### ISSUE THREAD

**Issue by crab2313** [rockchip-linux/rk-rootfs-build#32]
mk-rootfs.sh simply point to mk-rootfs-stretch.sh, which is trying to install armhf version of debs.
Should it be mk-rootfs-strech-arm64.sh ?

**Comment by dmitry1945** [comment]
Any updates?

**Comment by Caesar-github** [comment]
## Usage for 64bit Debian
Building a base debian system by ubuntu-build-service from linaro.

	sudo apt-get install binfmt-support qemu-user-static
	sudo dpkg -i ubuntu-build-service/packages/*
	sudo apt-get install -f
	RELEASE=stretch TARGET=desktop ARCH=arm64 ./mk-base-debian.sh

Building the rk-debian rootfs:

	RELEASE=stretch ARCH=arm64 ./mk-rootfs.sh

Building the rk-debain rootfs with debug:

	VERSION=debug ARCH=arm64 ./mk-rootfs-stretch-arm64.sh

Creating the ext4 image(linaro-rootfs.img):

	./mk-image.sh
---
