### ISSUE TITLE
Error during make-base-debian.sh

### ISSUE THREAD

**Issue by axendev** [rockchip-linux/rk-rootfs-build#35]
I am trying to build debian for rk3399 board. But make-base-debian.sh raises this error:
> [2019-04-04 15:26:14] lb chroot_apt install
> P: Configuring file /etc/apt/apt.conf
> [2019-04-04 15:26:14] lb chroot_archives chroot install
> P: Configuring file /etc/apt/sources.list
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> qemu: uncaught target signal 4 (Illegal instruction) - core dumped
> Illegal instruction (core dumped)
> P: Begin unmounting filesystems...
> P: Saving caches...
> if [ -f binary-tar.tar.gz ]; then \
>         tar -jcf linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 auto/ config/ configure; \
>         sudo mv binary.contents linaro-stretch-alip-`date +%Y%m%d`-1.contents; \
>         sudo mv chroot.packages.live linaro-stretch-alip-`date +%Y%m%d`-1.packages; \
>         sudo mv binary-tar.tar.gz linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz; \
>         md5sum linaro-stretch-alip-`date +%Y%m%d`-1.build-log.txt linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 linaro-stretch-alip-`date +%Y%m%d`-1.contents linaro-stretch-alip-`date +%Y%m%d`-1.packages linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz > linaro-stretch-alip-`date +%Y%m%d`-1.md5sums.txt; \
>         sha1sum linaro-stretch-alip-`date +%Y%m%d`-1.build-log.txt linaro-stretch-alip-`date +%Y%m%d`-1.config.tar.bz2 linaro-stretch-alip-`date +%Y%m%d`-1.contents linaro-stretch-alip-`date +%Y%m%d`-1.packages linaro-stretch-alip-`date +%Y%m%d`-1.tar.gz > linaro-stretch-alip-`date +%Y%m%d`-1.sha1sums.txt; \
>     fi
>  Failed to run livebuild, please check your network connection.

I think the problem is here:

> qemu: uncaught target signal 4 (Illegal instruction) - core dumped
> Illegal instruction (core dumped)
> P: Begin unmounting filesystems...

Can you help me to solve this ?

**Comment by axendev** [comment]
Full log of make-base-debian.sh: https://pastebin.com/MEgkNVnY

**Comment by mmabluesky** [comment]
@axendev 
I also encountered this error, now you solved this compilation error?

**Comment by rkchrome** [comment]
As the below log:
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
You can try to install the qemu-user-static package to /usr/bin.

Maybe the root cause is the network issue with your PC.
Can you access the google website with your network?

**Comment by axendev** [comment]
Hi,
My network is OK. "ping www.google.com" works fine. 
Could you provide rootfs compiled for aarch64, please ?

**Comment by rkchrome** [comment]
I think you can get the built image from https://github.com/rockchip-linux/docs/blob/master/SoC%20platform%20related/RK3399/Rockchip_RK3399_Linux_SDK_Release_V2.2.0_20190628_EN.pdf

**Comment by rkchrome** [comment]
Built images： https://eyun.baidu.com/s/3nwhJKjZ

**Comment by grkblood13** [comment]
same issue building buster for arm64

**Comment by JeffyCN** [comment]
Looks like something wrong in the host's qemu, please check the release note for suggested build system environments.

**Comment by HenriqueDeCanavarroAlencar** [comment]
Is possible run the command like super user? 
$ sudo lb chroot_archives chroot install
