### ISSUE TITLE
Latest libmali broke kmsdrm 

### ISSUE THREAD

**Issue by solskogen** [rockchip-linux/rk-rootfs-build#38]
The latest libmali file (libmali-rk-midgard-t76x-r14p0-r0p0_1.7-1_armhf.deb) does not work  with kms, like the earlier version did. 

Working deb file have md5sum: 891fcfe6ae2d188ca6706cd3399d517e
Non-working deb file (which is the latest in the repo) has: 31cfdf5a5a9ee4cc06df2468855ce7e0

**Comment by JeffyCN** [comment]
the libmali is closed source package, a workaround would be something like:
https://github.com/rockchip-linux/buildroot/blob/rockchip/2018.02-rc3/package/libdrm/0007-Skip-busid-check-in-drmOpenByName.patch
