### ISSUE TITLE
RK3399 ，No such element "rkximagesink"

### ISSUE THREAD

**Issue by xiangyue985** [rockchip-linux/rk-rootfs-build#40]
Hi rk:

  我的项目需要基于RK3399开发板移植UBUNTU 16.04 LTS;

  安装gstreamer&mpp deb包后，没有找到rkximagesink、rockchipmpp等element
 $gst-inspect-1.0  |grep rkximagesink
  
  使用usr/local/bin下的 test_dec-gst.sh脚本测试，提示“No such element rkximagesink”

  这个是DEB包没有安装成功吗？还是什么原因？

**Comment by xiangyue985** [comment]
这个是运行usr/local/bin下的 test_dec-gst.sh脚本测试的LOG:

  1stone@1Stone:/usr/local/bin$ export DISPLAY=:0.0
test.mp4  ! rkximagesink/bin$ gst-launch-1.0 uridecodebin uri=file:///usr/local/ 

(gst-plugin-scanner:410): GStreamer-WARNING **: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstgtksink.so': /usr/lib/aarch64-linux-gnu/mesa-egl/libEGL.so.1: undefined symbol: gbm_bo_create_with_modifiers

(gst-plugin-scanner:410): GStreamer-WARNING **: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstopengl.so': /usr/lib/aarch64-linux-gnu/mesa-egl/libEGL.so.1: undefined symbol: gbm_bo_create_with_modifiers
WARNING: erroneous pipeline: no element "rkximagesink"
1stone@1Stone:/usr/local/bin$

**Comment by JeffyCN** [comment]
ubuntu is not supported here.
