### ISSUE TITLE
RK3328 xorg 启动失败

### ISSUE THREAD

**Issue by kira2016** [rockchip-linux/rk-rootfs-build#41]
RELEASE=stretch TARGET=desktop ARCH=armhf ./mk-base-debian.sh
系统启动如果有执行/etc/init.d/rockchip.sh，xorg 启动失败；

[    17.265] 
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
[    17.271] Build Operating System: Linux 4.15.0-64-generic x86_64 Debian
[    17.274] Current Operating System: Linux linaro-alip 4.4.167-g17982fa-dirty #15 SMP Tue Nov 12 09:53:20 CST 2019 aarch64
[    17.277] Kernel command line: storagemedia=emmc androidboot.mode=emmc androidboot.slot_suffix= androidboot.serialno=c91917bb8e266ff2  rockchip_jtag rw rootwait earlyprintk=uart8250,0xff130000 swiotlb=1 kpti=0 console=ttyFIQ0 root=PARTUUID=614e0000-0000 rootfstype=ext4 systemd.gpt_auto=0 loglevel=8
[    17.290] Build Date: 05 March 2019  08:11:12PM
[    17.293] xorg-server 2:1.20.4-1 (https://www.debian.org/support) 
[    17.297] Current version of pixman: 0.34.0
[    17.301] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    17.306] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    17.332] (==) Log file: "/var/log/Xorg.0.log", Time: Wed Nov 13 09:59:51 2019
[    17.336] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    17.339] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    17.342] (==) No Layout section.  Using the first Screen section.
[    17.345] (**) |-->Screen "DefaultScreen" (0)
[    17.347] (**) |   |-->Monitor "<default monitor>"
[    17.350] (**) |   |-->Device "Mali FBDEV"
[    17.353] (==) No monitor specified for screen "DefaultScreen".
	Using a default monitor configuration.
[    17.355] (==) Automatically adding devices
[    17.357] (==) Automatically enabling devices
[    17.359] (==) Automatically adding GPU devices
[    17.363] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    17.366] (WW) The directory "/usr/share/fonts/X11/misc" does not exist.
[    17.368] 	Entry deleted from font path.
[    17.370] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    17.372] 	Entry deleted from font path.
[    17.375] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    17.377] 	Entry deleted from font path.
[    17.379] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    17.381] 	Entry deleted from font path.
[    17.383] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    17.385] 	Entry deleted from font path.
[    17.387] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    17.389] 	Entry deleted from font path.
[    17.392] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    17.394] 	Entry deleted from font path.
[    17.396] (==) FontPath set to:
	built-ins
[    17.398] (==) ModulePath set to "/usr/lib/xorg/modules"
[    17.400] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    17.403] (II) Loader magic: 0xaae22f98
[    17.406] (II) Module ABI versions:
[    17.408] 	X.Org ANSI C Emulation: 0.4
[    17.412] 	X.Org Video Driver: 24.0
[    17.416] 	X.Org XInput driver : 24.1
[    17.419] 	X.Org Server Extension : 10.0
[    17.424] (++) using VT number 7

[    17.426] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    17.431] (II) xfree86: Adding drm device (/dev/dri/card0)
[    17.435] (II) no primary bus or device found
[    17.437] 	falling back to /sys/devices/platform/display-subsystem/drm/card0
[    17.440] (II) LoadModule: "glx"
[    17.444] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    17.451] (II) Module glx: vendor="X.Org Foundation"
[    17.453] 	compiled for 1.20.4, module version = 1.0.0
[    17.456] 	ABI class: X.Org Server Extension, version 10.0
[    17.459] (II) LoadModule: "armsoc"
[    17.462] (WW) Warning, couldn't open module armsoc
[    17.465] (EE) Failed to load module "armsoc" (module does not exist, 0)
[    17.467] (EE) No drivers available.
[    17.470] (EE) 
Fatal server error:
[    17.480] (EE) no screens found(EE) 
[    17.497] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[    17.504] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[    17.512] (EE) 
[    17.526] (EE) Server terminated with error (1). Closing log file.
另外，

root@linaro-alip:/var/log# ls /sys/devices/platform/display-subsystem/drm/card0
card0-HDMI-A-1  dev  device  power  subsystem  uevent
root@linaro-alip:/var/log# ls /usr/local/first_boot_flag
/usr/local/first_boot_flag
附件是不启动rockchip这个服务的情况。
[Xorg.0.log](https://github.com/rockchip-linux/rk-rootfs-build/files/3840536/Xorg.0.log)

**Comment by JeffyCN** [comment]
need mk-rootfs-stretch.sh
