### ISSUE TITLE
debian10((Buster-32) Unable to log in to the desktop

### ISSUE THREAD

**Issue by atuxli** [rockchip-linux/rk-rootfs-build#42]
- According to the readme you provided, I compiled Debian 10-32 version. File system can run, I can log in through serial port, but there is no desktop, only terminal.

- my compliled cmd as fllow:

>   sudo apt-get install binfmt-support qemu-user-static 
>   sudo apt-get install python-dbus python-debian python-parted python-yaml  python-apt  u-boot-tools
>   sudo dpkg -i  python-support_1.0.15_all.deb   //install with deb
>   sudo dpkg -i ubuntu-build-service/packages/* 
>   sudo apt-get install -f
>   sudo  RELEASE=buster TARGET=desktop ARCH=armhf ./mk-base-debian.sh
>   sudo  RELEASE=buster ARCH=armhf ./mk-rootfs.sh
>   sudo  ./mk-image.sh`

- my hardware environment：
>  chip:  rk3288w
>  kernel: linux4.4 (rk-skd2.0)

- By the way , debian9-32 can log in desktop, it works very well。

- help, help, help !!!!!  I'm desperate for Wayland in debian10 !

**Comment by JeffyCN** [comment]
buster is no longer supported here, we are using https://github.com/rockchip-linux/distro for buster.
