### ISSUE TITLE
在AARCH64下ELFCLASS32错误

### ISSUE THREAD

**Issue by nickfox-taterli** [rockchip-linux/rk-rootfs-build#43]
平台是RK3399,重新build系统没解决,这几个文件似乎不是RK得,另外内存2GB+4GB(SWAP)是不足够?

root@linaro-alip:~# file /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstopenglmixers.so
/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstopenglmixers.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=47883215c85ff4a24882ee401d4a6fbbe8c6ade6, stripped

root@linaro-alip:~# test_dec-gst.sh 

(gst-plugin-scanner:716): GStreamer-WARNING **: 10:12:16.588: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstopenglmixers.so': libwayland-egl.so.1: wrong ELF class: ELFCLASS32

(gst-plugin-scanner:716): GStreamer-WARNING **: 10:12:16.762: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libcluttergst3.so': libwayland-egl.so.1: wrong ELF class: ELFCLASS32

(gst-plugin-scanner:716): GStreamer-WARNING **: 10:12:17.393: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstlibav.so': /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

(gst-plugin-scanner:716): GStreamer-WARNING **: 10:12:17.493: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstchromaprint.so': /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstRkXImageSink:rkximagesink0: Could not initialise X output
Additional debug info:
ximagesink.c(1603): gst_x_image_sink_xcontext_get (): /GstPipeline:pipeline0/GstRkXImageSink:rkximagesink0:
Could not open display
Setting pipeline to NULL ...
Freeing pipeline ...
/usr/local/bin/test_dec-gst.sh: 18: shift: can't shift that many

**Comment by JeffyCN** [comment]
libwayland-egl.so.1 is a link to libmali(rockchip gpu lib), so obviously the mk-rootfs-stretch.sh been called with wrong ARCH.
