### ISSUE TITLE
modify sources.list

### ISSUE THREAD

**Issue by atuxli** [rockchip-linux/rk-rootfs-build#44]
I suggest to modify the compilation shell: 
vim mk-rootfs-stretch.sh +91
echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ stretch main contrib non-free" > /etc/apt/sources.list
echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ stretch-updates main contrib non-free" >> /etc/apt/sources.list
echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ stretch-backports main contrib non-free" >> /etc/apt/sources.list
echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security stretch/updates main contrib non-free" >> /etc/apt/sources.list

**Comment by JeffyCN** [comment]
there are a few better ways to use chinese mirrors here, please google live build mirror for more details.
