### ISSUE TITLE
Not enough space to install Buster in mk-image

### ISSUE THREAD

**Issue by jveitchmichaelis** [rockchip-linux/rk-rootfs-build#45]
When I try and build buster (Rock960 / RK3399), the build fails because there isn't enough space in the output image (i.e. /dev/loop). I had to change `seek=4000` to `seek=4200`.

https://github.com/rockchip-linux/rk-rootfs-build/blob/master/mk-image.sh

**Comment by JeffyCN** [comment]
buster is no longer supported here
