### ISSUE TITLE
RK3399 debian 10 无法显示， 而且为什么跑起来那么卡？

### ISSUE THREAD

**Issue by jwzl** [rockchip-linux/rk-rootfs-build#49]
照着这个wiki 编译了一份debian 10 image， 跑起来后，没有图形系统, 没有vi, 安装也是无法启动， 感觉问题很多， 不知道是不是不支持RK3399还是 ？

**Comment by JeffyCN** [comment]
buster is no longer supported here

**Comment by JeffyCN** [comment]
FYI, we've upgraded to buster recently
