### ISSUE TITLE
release-20161015-stable - nfs client use is not possible with Debian 9 ?

### ISSUE THREAD

**Issue by pebauer68** [rockchip-linux/rk-rootfs-build#5]
sudo mount -t nfs -o proto=tcp,port=2049 192.168.x.x:/homeshare /media/myshare/
mount.nfs: No such device

I double checked that nfs-common is installed:
linaro@linaro-alip:~/tools$ sudo apt-get install nfs-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nfs-common is already the newest version (1:1.2.8-9.2).

**Comment by wzyy2** [comment]
try mount.nfs?
