### ISSUE TITLE
uboot gtp error

### ISSUE THREAD

**Issue by skyskyskysky** [rockchip-linux/rk-rootfs-build#52]
Relocation Offset is: 3ef0f000
MMC:   dwmmc@30000000: 1, dwmmc@30020000: 0
MMC partition switch failed
*** Warning - MMC partition switch failed, using default environment

In:    serial@11030000
Out:   serial@11030000
Err:   serial@11030000
Model: RK3229 Axolcore Series Board
switch to partitions #0, OK
mmc1 is current device
do_rkimg_test found IDB in SDcard
Boot from SDcard
rockchip_dnl_key_pressed adc_channel_single_shot fail!
get part misc fail -1
Net:   No ethernet found.
switch to partitions #0, OK
mmc1 is current device
GUID Partition Table Header signature is wrong: 0x0 != 0x5452415020494645
get_disk_guid: *** ERROR: Invalid GPT ***
GUID Partition Table Header signature is wrong: 0x0 != 0x5452415020494645
get_disk_guid: *** ERROR: Invalid Backup GPT ***
error!

**Comment by JeffyCN** [comment]
invalid gpt means invalid partition table in the firmware, which unlikely related to this repo(debian rootfs)
