### ISSUE TITLE
Debian9支持开机动画吗？

### ISSUE THREAD

**Issue by shiqx429** [rockchip-linux/rk-rootfs-build#54]
你好
我现在系统是Debian9，一切正常，就是没有开机启动动画，系统启动大概10秒黑屏，之后直接就到显示桌面了，我看系统里面已经带plymouth了，里面的文件也是全的，也看到开机启动动画的一堆图片，但我不知道怎么启动生效？

**Comment by JeffyCN** [comment]
for this kind of issue, please google related keywords(plus "rpi") firstly.

anyway, here's the steps to use plymouth on debian sdk:
1/ plymouth needs to be enabled in kernel's cmdline, and should not use the default console(which is serial console ttyFIQ0):
add these in kernel's config:
CONFIG_CMDLINE="splash plymouth.ignore-serial-consoles"
CONFIG_CMDLINE_EXTEND=y

2/ the hacky rockchip kernel logo might conflict with plymouth, so disable BSP u-boot logo or add this ExecStartPre to /lib/systemd/system/plymouth-start.service:
+ ExecStartPre=-/bin/sh -c 'echo 0 > /sys/class/graphics/fb0/blank'
ExecStart=/sbin/plymouthd --mode=boot --pid-file=/run/plymouth/pid --attach-to-sen
ExecStartPost=-/bin/plymouth show-splash
