### ISSUE TITLE
RK3288W- mali GPU issues

### ISSUE THREAD

**Issue by msmsubair** [rockchip-linux/rk-rootfs-build#59]
Is there a proper xserver and libmali version information for rk3288w mali chips which is r1p0 ?
i tried with Xserver 20 and  libamali 7, Xserver 19 and libmali 7, 6, 5 etc.. nothing works, latest libmali 9 gives an error lbmali truncated. in any case  glamor is not initializing, 
any idea ??

**Comment by JeffyCN** [comment]
i have no idea about what you were saying...

this SDK carries prebuilt and fix-version xserver and libmali, which are tested to work on rk3288w(unless something wrong in the kernel).

there's a boot time script to switching rk3288's libmali to rk3288w's, based on /sys/devices/platform/*gpu/gpuinfo
https://github.com/rockchip-linux/libmali/blob/master/overlay/S10libmali_rk3288
