### ISSUE TITLE
Debian 9 RFS, mounting of NFS share is not possbile

### ISSUE THREAD

**Issue by pebauer68** [rockchip-linux/rk-rootfs-build#6]
Pre-condition:  (NFS server is running)
The package nfs-common is installed:
linaro@linaro-alip:~/tools$ sudo apt-get install nfs-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
nfs-common is already the newest version (1:1.2.8-9.2).
The local forlder /media/myshare is present.

Testcase:
**Action:** (Mount nfs share with the following command)
**sudo mount -t nfs -o proto=tcp,port=2049 192.168.x.x:/homeshare /media/myshare/**
**Reaction:** (Error message below)
"mount.nfs: **No such device** "     /*nothing is mounted

Can you please try to re-produce this issue ?
It might be a configuration issue with NFS in Debian 9, but it worked before in Debian 8.

**Comment by wzyy2** [comment]
I just got this problem.
The reason is that nfs is not configured in the kernel .

**Comment by pebauer68** [comment]
Please configure NFS in the kernel, it is an important service for many people.
http://www.bitkistl.com/2017/03/asus-tinkerboard-questiones.html
