### ISSUE TITLE
adbd password check

### ISSUE THREAD

**Issue by bart112233** [rockchip-linux/rk-rootfs-build#60]
is there any way to enable password checking on adbd service?

**Comment by JeffyCN** [comment]
that adbd is a static linking version from rockchip buildroot SDK, it indeed carried a hack password patch:
https://github.com/JeffyCN/rockchip_mirrors/blob/buildroot/package/android-tools/0013-Support-requiring-login-for-adb-shell.patch

you can try to put a script like this under /usr/bin/ to enable it:
https://github.com/JeffyCN/rockchip_mirrors/blob/buildroot/package/android-tools/adb_auth.sh

but after all, why not just drop the adb and switch to ssh ;)
