### ISSUE TITLE
Unable to install Xorg on Ubuntu

### ISSUE THREAD

**Issue by mq002** [rockchip-linux/rk-rootfs-build#8]
I have tried several time to make ubuntu linux rootfs, but met with the same issue :(

root@localhost:/packages/xserver# dpkg -i *                                     
(Reading database ... 63455 files and directories currently installed.)         
Preparing to unpack xserver-common_1.18.21-4_all.deb ...                        
Unpacking xserver-common (2:1.18.21-4) over (2:1.18.4-0ubuntu0.2) ...           
Preparing to unpack xserver-xorg-core_1.18.21-4_armhf.deb ...                   
Unpacking xserver-xorg-core (2:1.18.21-4) over (2:1.18.4-0ubuntu0.2) ...        
Setting up xserver-common (2:1.18.21-4) ...                                     
dpkg: dependency problems prevent configuration of xserver-xorg-core:           
 xserver-xorg-core depends on libgcrypt20 (>= 1.7.0); however:                  
  Version of libgcrypt20:armhf on system is 1.6.5-2ubuntu0.2.                   
                                                                                
dpkg: error processing package xserver-xorg-core (--install):                   
 dependency problems - leaving unconfigured                                     
Processing triggers for man-db (2.7.5-1) ...                                    
Errors were encountered while processing:                                       
 xserver-xorg-core                

Can rockchip provide rootfs image just like debian 9 ?

**Comment by wzyy2** [comment]
We don't have plan to support other distribution.. 
One distribution for demo and develop linux components is enough.

You can modify https://github.com/rockchip-linux/xserver/blob/rockchip-1.18/debian/control according to the ubuntu‘s depends and recompile package.
