### ISSUE TITLE
bluetooth(ap6335)  can't work  with kernel4.4 and rk-rootfs-build filesystem

### ISSUE THREAD

**Issue by liuqsqq** [rockchip-linux/rk-rootfs-build#9]
1、our enviroment is as follows:
cpu:rk3288
kernel: 4.4, https://github.com/rockchip-linux/kernel.git
filesystem: just this filesystem or our customed filesystem(ubuntu 16.04-base)
**I tried to use commands:
rfkill list->rfkill unblock all->hciattach->hcitool scan
or                                    -> brcm_patchram_plus->hciattach->hcitool scan
However, none works well.
The follwings are the detail procedures:**
2、when system is power up, i did serveral steps as follows: 
 **(1)root@linaro-alip:~# rfkill list**
       0: bt_default: Bluetooth
        Soft blocked: yes
        Hard blocked: no
      1: phy0: Wireless LAN
        Soft blocked: no
        Hard blocked: no
     2: brcmfmac-wifi: Wireless LAN
        Soft blocked: no
        Hard blocked: no
    bluetooth is blocked by soft,then we unblock it 
  **(2)root@linaro-alip:~# rfkill unblock all**
        [  241.135126] [BT_RFKILL]: ENABLE UART_RTS
        [  241.245148] [BT_RFKILL]: DISABLE UART_RTS
        [  241.249583] [BT_RFKILL]: bt turn on power
   **but, root@linaro-alip:~# hciconfig  -a,this command show up nothing.**
  **(3) I used hciattach tool to bing uart and hci according to the docments in web. Also i wanto download the bcm4339a0.hcd to bluetooth chip(ap6335) with hciattach**
root@linaro-alip:~# hciattach -s 115200 /dev/ttyS0 bcm43xx 115200
[  422.812895] ttyS0 - failed to request DMA
bcm43xx_init
bcm43xx_reset, 105
bcm43xx_reset, 110
bcm43xx_reset, 116
Set Controller UART speed to 115200 bit/s
Flash firmware /etc/firmware/BCM4335C0.hcd
Initialization timed out.
**well, the path that we want to download of bcm4339ao.hcd is  /system/vendor/firmware/bcm4339a0.hcd.**
**(4)However, the following  command works well:**
       root@linaro-alip:/# hciattach -s 115200 /dev/ttyS0 any
       Device setup complete
       root@linaro-alip:/# hcitool cmd 0x03 0x001A 0x03
       HCI Command: ogf 0x03, ocf 0x001a, plen 1
       03 
       HCI Event: 0x0e plen 4
       01 1A 0C 00 
       root@linaro-alip:/# hciconfig -a
   hci0:   Type: Primary  Bus: UART
        BD Address: 6B:88:8C:01:08:05  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING PSCAN ISCAN 
        RX bytes:759 acl:0 sco:0 events:48 errors:0
        TX bytes:2793 acl:0 sco:0 commands:48 errors:0
        Features: 0xbf 0xfe 0xcf 0xff 0xdf 0xff 0x7b 0x8f
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3 
        Link policy: RSWITCH SNIFF 
        Link mode: SLAVE ACCEPT 
        Name: 'linaro-alip'
        Class: 0x000000
        Service Classes: Unspecified
        Device Class: Miscellaneous, 
        HCI Version: 4.0 (0x6)  Revision: 0x0
        LMP Version: 4.0 (0x6)  Subversion: 0x6109
        Manufacturer: Broadcom Corporation (15)
**at this time , i can find the bluetooth device, but when i execute "hcitool scan", nothing shows up.
root@linaro-alip:/# hcitool scan
Scanning ...**
**(5)I also try to down the hcd file to ap6335 by a tool named  brcm_patchram_plus.**
root@linaro-alip:/home/linaro# ./brcm_patchram_plus -d --patchram  /system/vendor/firmware/bcm4339a0.hcd --baudrate 1500000 --enable_lpm --enable_hci /dev/ttyS0
the log are as follows: 
option baudrate with arg 1500000
option enable_lpm
option enable_hci
/dev/ttyS0 
writing
01 03 0c 00 
received 7
04 0e 04 01 03 0c 00 
writing
01 2e fc 00 
received 7
04 0e 04 01 2e fc 00 
**Something  seems to be faied when brcm_patchram_plus  try to download hcd file to the bluetooth chip.**
**(6)For the moment , i have no others ways to driver the bluetooth, would you please give me some suggestions? Thanks!**

**Comment by wzyy2** [comment]
Could you try 'hciattach /dev/ttyS0 bcm43xx 115200 noflow nosleep 00:11:22:33:44:55 -t 20' or move /system/vendor/firmware/bcm4339a0.hcd to  /etc/firmware/?
